### ISSUE TITLE
Preprocessed dataset for CoNSeP and MoNuSAC

### ISSUE THREAD

**Issue by mustansarfiaz** [dair-iitd/DeGPR#1]
Hi,

I found your work very interesting and want to reproduce the numbers for CoNSeP and MoNuSAC datasets. 
Can you please provide the preprocessed CoNSeP and MoNuSAC datasets for your remarkable work?

And also please provide your datasets 

train_data_path = Path('/home/aayush/Aayush/Projects/Celiac_Disease/Detection/Baselines/Dataset/voc_kfold/0/train_val/VOC2007/JPEGImages')
#Paths where to save the generated dataframes
TRAIN_CSV = "/home/aayush/Aayush/Projects/Celiac_Disease/Detection/Baselines/Dataset/voc_kfold_csv/0/train_data.csv"
VALID_CSV = "/home/aayush/Aayush/Projects/Celiac_Disease/Detection/Baselines/Dataset/voc_kfold_csv/0/valid_data.csv"
TEST_CSV  = "/home/aayush/Aayush/Projects/Celiac_Disease/Detection/Baselines/Dataset/voc_kfold_csv/0/test_data.csv

Thank you.

Mustansar

**Comment by chiragmohapatra** [comment]
I have added the data_preprocessing folder. You can make the process the CoNSeP and MoNuSAC datasets following the steps there.
