### ISSUE TITLE
preprocessed data-science-bowl-2018 dataset

### ISSUE THREAD

**Issue by mustansarfiaz** [dair-iitd/DeGPR#2]
Hi,

It would be good if you please provide the preprocessed datasets.

Regards

**Comment by Aayushktyagi** [comment]
Hi,

You can find preprocessed kaggle data science bowl dataset [here](https://drive.google.com/drive/folders/1vHVTilQWaevtacianJkANNCzwkRlby1O?usp=sharing). 
Dataset is present in yolo format. 

Thanks 
Aayush

**Comment by mustansarfiaz** [comment]
Hi 

Thank you
