### ISSUE TITLE
Error to compute PCA embeddings_pca_model.transform 

### ISSUE THREAD

**Issue by mustansarfiaz** [dair-iitd/DeGPR#3]
Hi,

I found that the method catches exceptions at Detection/faster_rcnn/engine.py#L292
https://github.com/dair-iitd/DeGPR/blob/a479c801d882fbb086f118e671170e45dad10d6a/Detection/faster_rcnn/engine.py#L292

How to resolve it.

The error is:
line # 292: target_transform = embeddings_pca_model.transform(target_shape[i1].reshape(1,-1))
*** AttributeError: 'NoneType' object has no attribute 'transform'

Regards
Mustansar

**Comment by Aayushktyagi** [comment]
Hey @mustansarfiaz,

We are working on it. All the additional data, methods, cleaner code and instructions of how to run code should be up in next 1-2 days. 

Thanks 
Aayush

**Comment by mustansarfiaz** [comment]
Hi

Thank you
